language: php
php:
 - 5.5
 - 5.4
 - 5.3
before_script:
 - composer install
 - pyrus install pear/PHP_CodeSniffer

script:
 - mkdir -p build/logs
 - phpcs --standard=PSR2 src/
 - phpcs --standard=PSR2 tests/
 - phpunit
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls
